/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_fenetre_ajouter_capteur (void);
GtkWidget* create_fenetre_afficher_capteur (void);
GtkWidget* create_menu_capteurs (void);
GtkWidget* create_fenetre_rechercher_capteur (void);
GtkWidget* create_fenetre_supprimer_capteur (void);
GtkWidget* create_fenetre_modifier_capteur (void);
GtkWidget* create_fenetre_ajouter_valeur (void);
GtkWidget* create_menu_principal (void);
GtkWidget* create_fenetre_ajout_ouvrier (void);
GtkWidget* create_fenetre_afficher_ouvrier (void);
GtkWidget* create_menu_ouvriers (void);
GtkWidget* create_fenetre_rechercher_ouvrier (void);
GtkWidget* create_fenetre_supprimer_ouvrier (void);
GtkWidget* create_fenetre_modifier_ouvrier (void);
GtkWidget* create_modification_ouvrier (void);
GtkWidget* create_fenetre_ajouter (void);
GtkWidget* create_fenetre_afficher (void);
GtkWidget* create_menu_client (void);
GtkWidget* create_rechercher_client (void);
GtkWidget* create_supprimer_client (void);
GtkWidget* create_modifier_client (void);
GtkWidget* create_modification_client (void);
GtkWidget* create_rendezvous_client (void);
GtkWidget* create_plus_seche (void);
GtkWidget* create_fenetre_ajouter_troupeau (void);
GtkWidget* create_fenetre_afficher_troupeau (void);
GtkWidget* create_menu_troupeaux (void);
GtkWidget* create_fenetre_rechercher_troupeau (void);
GtkWidget* create_fenetre_supprimer_troupeau (void);
GtkWidget* create_fenetre_modifier_troupeau (void);
GtkWidget* create_modification_troupeau (void);
