/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
GtkWidget *menu_principal;
  /*GtkWidget *fenetre_ajouter_capteur;
  GtkWidget *fenetre_afficher_capteur;
  
  GtkWidget *fenetre_rechercher_capteur;
  GtkWidget *fenetre_supprimer_capteur;
  GtkWidget *fenetre_modifier_capteur;*/

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  /*fenetre_ajouter_capteur = create_fenetre_ajouter_capteur ();
  gtk_widget_show (fenetre_ajouter_capteur);
  fenetre_afficher_capteur = create_fenetre_afficher_capteur ();
  gtk_widget_show (fenetre_afficher_capteur);*/
  //menu_capteurs = create_menu_capteurs ();
  //gtk_widget_show (menu_capteurs);
  /*fenetre_rechercher_capteur = create_fenetre_rechercher_capteur ();
  gtk_widget_show (fenetre_rechercher_capteur);
  fenetre_supprimer_capteur = create_fenetre_supprimer_capteur ();
  gtk_widget_show (fenetre_supprimer_capteur);
  fenetre_modifier_capteur = create_fenetre_modifier_capteur ();
  gtk_widget_show (fenetre_modifier_capteur);*/
 menu_principal = create_menu_principal();
  gtk_widget_show (menu_principal);

  gtk_main ();
  return 0;
}

